### PR TITLE
Add patch to sever path/inode connection on clobber()

### PR DESCRIPTION
**Pull request by nehaljwani**
xref: https://github.com/conda/conda/issues/6861

### CODE REVIEW

**Comment by nehaljwani** [comment]
cc @goanpeca

**Comment by kalefranz** [comment]
Is that really the only one? Is it really that simple?

**Comment by nehaljwani** [comment]
I tested it only with a pip install /path|link/to/tarball and /path|link/to/wheel

I didn't try anything else.

**Comment by kalefranz** [comment]
Well I guess that’s a good start

**Comment by jjhelmus** [comment]
Should we report this issue upstream, https://github.com/pypa/pip, and try to get the patch included in the next pip release?  I searched through the issues and was not able to find anything that mentioned this behavior.

**Comment by nehaljwani** [comment]
I'll need a perfect example to show upstream before I send it to pypa. 

Till then, I'm merging this. :crossed_fingers:

**Comment by kalefranz** [comment]
🎉

**Comment by kalefranz** [comment]
There's probably a good example in issues linked at https://github.com/conda/conda/issues/6861 or at https://github.com/conda/conda/issues/6079

**Comment by kiwi0fruit** [comment]
@nehaljwani I've just encountered behaviour that indicates that this issue id not over:

When having conda cython v0.28.2 and installing a package that depend on higher version of cython: `"cython>=0.28.3"` (or pip installing higher version cython itself) pip uninstalls conda's cython and installs.

**Comment by kalefranz** [comment]
@kiwi0fruit see response at conda/conda#6861 (comment)

**Pull request merged**
